import Foundation

// MARK: - MemoryCategory

enum MemoryCategory: String, Codable, CaseIterable {
    case project
    case preference
    case correction
    case note
    case taskSummary

    var label: String {
        switch self {
        case .project:     return "Project"
        case .preference:  return "Preference"
        case .correction:  return "Correction"
        case .note:        return "Note"
        case .taskSummary: return "Task Summary"
        }
    }

    var badge: String {
        switch self {
        case .project:     return "P"
        case .preference:  return "⚙"
        case .correction:  return "✎"
        case .note:        return "✦"
        case .taskSummary: return "✓"
        }
    }
}

// MARK: - MemoryEntry

struct MemoryEntry: Codable, Identifiable {
    let id: UUID
    let category: MemoryCategory
    var content: String
    let createdAt: Date
    var updatedAt: Date
    var source: String?
    var pinned: Bool

    init(
        id: UUID = UUID(),
        category: MemoryCategory,
        content: String,
        createdAt: Date = Date(),
        updatedAt: Date = Date(),
        source: String? = nil,
        pinned: Bool = false
    ) {
        self.id = id
        self.category = category
        self.content = content
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.source = source
        self.pinned = pinned
    }
}

// MARK: - MemoryStore

final class MemoryStore {

    static let shared = MemoryStore()
    static let didChange = Notification.Name("MemoryStore.didChange")

    private(set) var memories: [MemoryEntry] = []

    private let fileURL: URL = {
        let support = FileManager.default.urls(
            for: .applicationSupportDirectory,
            in: .userDomainMask
        ).first ?? FileManager.default.temporaryDirectory
        let dir = support.appendingPathComponent("Flock", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("memories.json")
    }()

    private let maxMemories = 200

    private init() {
        restore()
    }

    // MARK: - Filtered accessors

    var pinned: [MemoryEntry] {
        memories.filter { $0.pinned }
    }

    func memories(for category: MemoryCategory) -> [MemoryEntry] {
        memories.filter { $0.category == category }
    }

    var taskSummaries: [MemoryEntry] {
        memories.filter { $0.category == .taskSummary }
    }

    // MARK: - Mutations

    func add(_ entry: MemoryEntry) {
        memories.insert(entry, at: 0)
        trimIfNeeded()
        didMutate()
    }

    func addMemory(category: MemoryCategory, content: String, source: String? = nil) {
        let entry = MemoryEntry(category: category, content: content, source: source)
        add(entry)
    }

    func addTaskSummary(taskTitle: String, summary: String, cost: Double?) {
        var content = "Task: \(taskTitle)\n\(summary)"
        if let cost = cost {
            content += "\nCost: $\(String(format: "%.4f", cost))"
        }
        addMemory(category: .taskSummary, content: content, source: taskTitle)
    }

    func update(_ entry: MemoryEntry, content: String) {
        guard let idx = memories.firstIndex(where: { $0.id == entry.id }) else { return }
        memories[idx].content = content
        memories[idx].updatedAt = Date()
        didMutate()
    }

    func togglePin(_ entry: MemoryEntry) {
        guard let idx = memories.firstIndex(where: { $0.id == entry.id }) else { return }
        memories[idx].pinned.toggle()
        didMutate()
    }

    func remove(_ entry: MemoryEntry) {
        memories.removeAll { $0.id == entry.id }
        didMutate()
    }

    func removeAll(category: MemoryCategory? = nil) {
        if let category = category {
            memories.removeAll { $0.category == category }
        } else {
            memories.removeAll()
        }
        didMutate()
    }

    // MARK: - Context File Generation

    /// Writes a `.flock-context.md` file in the given directory with relevant memories.
    /// Pass `excludingPaneId` to filter journal entries from the requesting pane.
    func writeContextFile(to directory: String, excludingPaneId: UUID? = nil) {
        guard Settings.shared.memoryEnabled else { return }
        guard !memories.isEmpty else { return }

        let fileURL = URL(fileURLWithPath: directory).appendingPathComponent(".flock-context.md")

        var lines: [String] = []
        lines.append("# Flock Memory Context")
        lines.append("")
        lines.append("This file is auto-generated by Flock. It contains persistent context from previous sessions.")
        lines.append("Do not edit manually -- manage through Flock's memory panel (⌘⇧M).")
        lines.append("")

        // Pinned memories first
        let pinnedEntries = pinned
        if !pinnedEntries.isEmpty {
            lines.append("## Pinned")
            lines.append("")
            for entry in pinnedEntries {
                lines.append("- **[\(entry.category.label)]** \(entry.content)")
            }
            lines.append("")
        }

        // Group remaining by category
        for category in MemoryCategory.allCases {
            let entries = memories.filter { $0.category == category && !$0.pinned }
            guard !entries.isEmpty else { continue }

            lines.append("## \(category.label)")
            lines.append("")
            for entry in entries.prefix(20) {
                let content = entry.content.replacingOccurrences(of: "\n", with: " ")
                lines.append("- \(content)")
            }
            if entries.count > 20 {
                lines.append("- ... and \(entries.count - 20) more")
            }
            lines.append("")
        }

        // Journal context: what other agents have done recently
        if Settings.shared.journalEnabled,
           let journalContext = FlockJournal.shared.contextBriefing(excludingPane: excludingPaneId ?? UUID()) {
            lines.append(journalContext)
        }

        let text = lines.joined(separator: "\n")
        try? text.write(to: fileURL, atomically: true, encoding: .utf8)
    }

    /// Removes the `.flock-context.md` file from a directory.
    func removeContextFile(from directory: String) {
        let fileURL = URL(fileURLWithPath: directory).appendingPathComponent(".flock-context.md")
        try? FileManager.default.removeItem(at: fileURL)
    }

    // MARK: - Persistence

    private func didMutate() {
        save()
        NotificationCenter.default.post(name: MemoryStore.didChange, object: self)
    }

    func save() {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = .prettyPrinted
        guard let data = try? encoder.encode(memories) else { return }
        try? data.write(to: fileURL, options: .atomic)
    }

    func restore() {
        guard let data = try? Data(contentsOf: fileURL) else { return }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard let loaded = try? decoder.decode([MemoryEntry].self, from: data) else { return }
        memories = loaded
    }

    private func trimIfNeeded() {
        guard memories.count > maxMemories else { return }
        // Keep pinned, remove oldest unpinned
        let unpinned = memories.filter { !$0.pinned }
            .sorted { $0.createdAt > $1.createdAt }
        let excess = memories.count - maxMemories
        let toRemove = Set(unpinned.suffix(excess).map { $0.id })
        memories.removeAll { toRemove.contains($0.id) }
    }
}
